# mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: admin
# jsp
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  #security:
   # user:
    #  name: admin
     # password: password